name: sns-final

dependencies:
  - python=3.7
  - pip
  - pip:
    - numpy
    - requests
    - pandas
    - jupyter
    - jupyterlab
    - requests
    - seaborn
    - scipy
    - sklearn
    - tensorflow
    - keras
    - scikit-learn
    

 
    


